# Generated by Django 4.2 on 2023-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_remove_step_parent_step_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='contents',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
